job/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('vacancies.urls')),
    path('users/',include('users.urls',namespace='users'))
    
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordChangeView,PasswordChangeDoneView
from . import views 
app_name='users'

urlpatterns=[
    path('login/',views.LoginUser.as_view(),name='login'),
    path('logout/', views.logout_user,name='logout'),
    path('password-change/',views.UserPasswordChange.as_view(),name='password_change'),
    path('password-change/done/',PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),name='password_change_done'),
    path('register/',views.RegisterUser.as_view(),name='register'),
    path('profile/',views.ProfileUser.as_view(),name='profile'),


]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm,PasswordChangeForm
from django.contrib.auth import get_user_model




class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',widget=forms.TextInput(attrs={'class':'form-input'}))
    password=forms.CharField(label='Пароль',widget=forms.PasswordInput(attrs={'class':'form-input'}))
    
    class Meta:
        model=get_user_model()
        fields=['username', 'password']


class RegisterUserForm(UserCreationForm):
    username=forms.CharField(label='Логин',widget=forms.TextInput(attrs={'class':'form-input'}))
    password1 = forms.CharField(label='Пароль',widget=forms.PasswordInput(attrs={'class':'form-input'}))
    password2=forms.CharField(label='Повтор пароля',widget=forms.PasswordInput(attrs={'class':'form-input'}))


    class Meta:
        model=get_user_model()
        fields=['username','email','first_name','last_name','password1','password2']
        labels={
            'email':'E-mail',
            'first_name':'Имя',
            'last_name':'Фамилия',
        }
        widgets={
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


    def clean_mail(self):   
        email=self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exist():
            raise forms.ValidationError('Такой E-mail уже существует!')
        return email
"""    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password']!=cd['password2']:
            raise forms.ValidationError('Пароли не совпадают!')
        return cd['password2']
        """

    
class ProfileUserForm(forms.ModelForm):
    username=forms.CharField(disabled=True,label='Логин',widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model=get_user_model()
        fields=['username','email','first_name','last_name']
        labels={
            'first_name':'Имя',
            'last_name':'Фамилия',
            }
        widgets={
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
            }
        
class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

users/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate ,login,logout
from django.shortcuts import render,HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from .forms import LoginUserForm, ProfileUserForm,RegisterUserForm, UserPasswordChangeForm
from django.views.generic.edit import CreateView,UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.views import PasswordChangeView



class RegisterUser(CreateView):
    form_class=RegisterUserForm
    template_name='users/register.html'
    success_url=reverse_lazy('users:login')
    extra_content={
        'title': 'Регистрация',
    }

class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}


"""def register(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request,'users/register_done.html')
    else:
        form = RegisterUserForm()
    return render(request,'users/register.html',{'form':form})
"""

class ProfileUser(LoginRequiredMixin,UpdateView):
    model = get_user_model()
    form_class=ProfileUserForm
    template_name='users/profile.html'
    extra_context = {'title': "Профиль пользователя"}

    def get_success_url(self) -> str:
        return reverse_lazy('users:profile',args=[self.request.user.pk])
    
    def get_object(self,queryset = None):
        return self.request.user



class LoginUser(LoginView):
    form_class=AuthenticationForm
    template_name='users/login.html'
    extra_context={'title':'Авторизация'}



def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

users/templates/users/login.html
{%extends 'base.html'%}
{%block content %}
<h1>Авторизация</h1>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <div class="form-error">{{ form.non_field_errors }}</div>
 
    {% for f in form %}
    <p ><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Войти</button></p>
</form>
{%endblock%}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль успешно изменен!</h1>
 
<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

users/templates/users/password_change_form.html
{%extends 'base.html'%}
{%block content%}
<h1>Изменение пароля</h1>
<form  method="post">
    {%csrf_token%}
    <div class="form-error">{{form.non_field_errors}}</div>
    {%for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {%endfor%}
    <p ><button type="submit">Изменить пароль</button></p>  
</form>
{%endblock%}

users/templates/users/profile.html
{%extends 'base.html'%}

{%block content%}
<form method="post"></form>
{%csrf_token%}
<div class="form-error">{{form.non_field_errors}}</div>
{%for f in form%}
<p><label class="form-label" for="{{f.id_for_label}}">{{f.label}}: </label>{{f}}</p>
<div class="form-error"> {{f.errors}}</div>
{%endfor%}
<p><button type="submit">Save</button></p>
<hr>
<p><a href="{%url 'users:password_change'%}">Сменить пароль</a></p>
{%endblock%}

users/templates/users/register.html
{%extends 'base.html'%}

{%block content%}
<h1>Регистрация</h1>
<form action="" method= 'post'>
    {%csrf_token%}
    <input type="hidden" name="next" value="{{next}}"/>
    <div class="form-error">{{form.non_field_errors}}</div>
    {% for f in form%}
        <p><label for="{{f.id_for_label}}" class="form-label">{{f.label}}:</label>{{f}}</p>
        <div class="form-error">{{f.errors}}</div>
    {%endfor%}
    
    <p><button type="submit">Регистрация</button></p>
</form>
{%endblock%}

users/templates/users/register_done.html
{%extends 'base.html'%}
{% block content%}
<h1>Добро пожаловать!</h1>
<p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой <a href="{%url 'users:login'%}">ссылке</a></p>
{%endblock%}