job/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('vacancies.urls')),
    path('users/',include('users.urls',namespace='users'))
    
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordChangeView,PasswordChangeDoneView
from . import views 
app_name='users'

urlpatterns=[
    path('login/',views.LoginUser.as_view(),name='login'),
    path('logout/', views.logout_user,name='logout'),
    path('password-change/',views.UserPasswordChange.as_view(),name='password_change'),
    path('password-change/done/',PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),name='password_change_done'),
    path('register/',views.RegisterUser.as_view(),name='register'),
    path('profile/',views.ProfileUser.as_view(),name='profile'),


]

templates/base.html
{% load static %}
{%load vacancies_tags%}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vacancies/css/style.css'%}"/>
    <title>ITJob</title>
</head>
<body>

{%block mainmenu %}
<div class="header">
<h1><a class="ITJob" href="{%url 'home' %}">ITJob</a></h1>
<nav>
        <ul>
            <!-- {%get_menu as menu%} -->
            {%for m in mainmenu%}
            <li><a href="{% url m.url_name%}">{{m.title}}</a></li>
            {%endfor%}
            {%if user.is_authenticated%}
            <li class="last"> <a href="{% url 'users:profile' %}">{{user.username}}</a> | <a href="{% url 'users:logout' %}">Выйти</a></li>
            {%else%}
            <li class="last"><a href="{%url 'users:login'%}">Войти </a>| <a href="{% url 'users:register'%}">Регистрация</a></li>
            {%endif%}
        </ul>
        <div class="clear"></div>
</nav>
</div>
{%endblock%}
<div class="sidebar">
    <h2>Навигация</h2>
    <ul>
        {%show_categories %}
        <!-- <li class="selected">Все вакансии</li> -->
    </ul>
</div>
<div class="main-content"> 
    <!-- Список вакансий -->
    {%block list_post%} 
    {%endblock%}
</div>
<!-- Описание вакансии -->
<div class="content">    
    {%block content%}
    {%endblock%}
    <!-- Добавьте больше карточек с вакансиями по необходимости -->    
</div>

<div class="content">    
    {%block addjob%}
    {%endblock%}
    <!-- Добавьте больше карточек с вакансиями по необходимости -->    
</div>


</body>
</html>